export const customerData = [
    {
      customerName: 'Elena Rodriguez',
      status: 'standard',
      shippingService: 'priority',
      address: {
        street: 'east st',
        suite: 'Apt 101',
        city: 'Chennai',
        country: 'India',
        zipCode: '28001',
      },
    },
    {
      customerName: 'YIndiai Tanaka',
      status: 'express',
      shippingService: 'standard',
      address: {
        street: 'main st',
        suite: '',
        city: 'Chennai',
        country: 'India',
        zipCode: '100-0004',
      },
    },
    {
      customerName: 'Anna Müller',
      status: 'priority',
      shippingService: 'express',
      address: {
        street: 'berlin st',
        suite: 'Apt 203',
        city: 'Chennai',
        country: 'India',
        zipCode: '10178',
      },
    },
    {
      customerName: 'Carlos Silva',
      status: 'express',
      shippingService: 'priority',
      address: {
        street: 'copacabana st',
        suite: '',
        city: 'Chennai',
        country: 'India',
        zipCode: '22020-002',
      },
    },
    {
      customerName: 'Mei Chen',
      status: 'standard',
      shippingService: 'express',
      address: {
        street: 'pudong st',
        suite: 'Apt 501',
        city: 'Chennai',
        country: 'India',
        zipCode: '200120',
      },
    },
    {
      customerName: 'Ivan Petrov',
      status: 'priority',
      shippingService: 'standard',
      address: {
        street: 'red square st',
        suite: '',
        city: 'Chennai',
        country: 'India',
        zipCode: '103073',
      },
    },
    {
      customerName: 'Sophie Dupont',
      status: 'express',
      shippingService: 'priority',
      address: {
        street: 'champs-elysees st',
        suite: 'Apt 401',
        city: 'Trichy',
        country: 'India',
        zipCode: '75008',
      },
    },
    {
        customerName: 'John Joe',
        status: 'standard',
        shippingService: 'express',
        address: {
          street: 'north st',
          suite: '',
          city: 'Trichy',
          country: 'India',
          zipCode: '10001',
        },
      },
      {
        customerName: 'Alice Johnson',
        status: 'priority',
        shippingService: 'standard',
        address: {
          street: 'west st',
          suite: 'Apt 302',
          city: 'Trichy',
          country: 'India',
          zipCode: '931762',
        },
      },
      {
        customerName: 'Bob Smith',
        status: 'express',
        shippingService: 'priority',
        address: {
          street: 'south st',
          suite: '',
          city: 'Trichy',
          country: 'India',
          zipCode: '2000',
        },
      },
      {
        customerName: 'John Joe',
        status: 'standard',
        shippingService: 'express',
        address: {
          street: 'north st',
          suite: '',
          city: 'Trichy',
          country: 'India',
          zipCode: '10001',
        },
      },
      {
        customerName: 'Alice Johnson',
        status: 'priority',
        shippingService: 'standard',
        address: {
          street: 'west st',
          suite: 'Apt 302',
          city: 'Trichy',
          country: 'India',
          zipCode: '97398464',
        },
      },
      {
        customerName: 'Bob Smith',
        status: 'express',
        shippingService: 'priority',
        address: {
          street: 'south st',
          suite: '',
          city: 'Trichy',
          country: 'India',
          zipCode: '2000',
        },
      },
    {
      customerName: 'Elena Rodriguez',
      status: 'standard',
      shippingService: 'priority',
      address: {
        street: 'east st',
        suite: 'Apt 101',
        city: 'Coimbatore',
        country: 'India',
        zipCode: '28001',
      },
    },
    {
      customerName: 'YIndiai Tanaka',
      status: 'express',
      shippingService: 'standard',
      address: {
        street: 'main st',
        suite: '',
        city: 'Coimbatore',
        country: 'India',
        zipCode: '100-0004',
      },
    },
    {
      customerName: 'Anna Müller',
      status: 'priority',
      shippingService: 'express',
      address: {
        street: 'berlin st',
        suite: 'Apt 203',
        city: 'Coimbatore',
        country: 'India',
        zipCode: '10178',
      },
    },
    {
      customerName: 'Carlos Silva',
      status: 'express',
      shippingService: 'priority',
      address: {
        street: 'copacabana st',
        suite: '',
        city: 'Coimbatore',
        country: 'India',
        zipCode: '22020-002',
      },
    },
    {
      customerName: 'Mei Chen',
      status: 'standard',
      shippingService: 'express',
      address: {
        street: 'pudong st',
        suite: 'Apt 501',
        city: 'Coimbatore',
        country: 'India',
        zipCode: '200120',
      },
    },
    {
      customerName: 'Ivan Petrov',
      status: 'priority',
      shippingService: 'standard',
      address: {
        street: 'red square st',
        suite: '',
        city: 'Coimbatore',
        country: 'India',
        zipCode: '103073',
      },
    },
    {
      customerName: 'Sophie Dupont',
      status: 'express',
      shippingService: 'priority',
      address: {
        street: 'champs-elysees st',
        suite: 'Apt 401',
        city: 'Salem',
        country: 'India',
        zipCode: '75008',
      },
    },
    {
        customerName: 'John Joe',
        status: 'standard',
        shippingService: 'express',
        address: {
          street: 'north st',
          suite: '',
          city: 'Salem',
          country: 'India',
          zipCode: '10001',
        },
      },
      {
        customerName: 'Alice Johnson',
        status: 'priority',
        shippingService: 'standard',
        address: {
          street: 'west st',
          suite: 'Apt 302',
          city: 'Salem',
          country: 'India',
          zipCode: '983688',
        },
      },
      {
        customerName: 'Bob Smith',
        status: 'express',
        shippingService: 'priority',
        address: {
          street: 'south st',
          suite: '',
          city: 'Salem',
          country: 'India',
          zipCode: '2000',
        },
      },
      {
        customerName: 'John Joe',
        status: 'standard',
        shippingService: 'express',
        address: {
          street: 'north st',
          suite: '',
          city: 'Salem',
          country: 'India',
          zipCode: '10001',
        },
      },
      {
        customerName: 'Alice Johnson',
        status: 'priority',
        shippingService: 'standard',
        address: {
          street: 'west st',
          suite: 'Apt 302',
          city: 'Salem',
          country: 'India',
          zipCode: '69733145',
        },
      },
      {
        customerName: 'Bob Smith',
        status: 'express',
        shippingService: 'priority',
        address: {
          street: 'south st',
          suite: '',
          city: 'Salem',
          country: 'India',
          zipCode: '2000',
        },
      },
      {
        customerName: 'Jane Doe',
        status: 'standard',
        shippingService: 'express',
        address: {
          street: 'west st',
          suite: 'Apt 105',
          city: 'Madurai',
          country: 'India',
          zipCode: '90001',
        },
      },
      {
        customerName: 'Miguel Rodriguez',
        status: 'express',
        shippingService: 'standard',
        address: {
          street: 'calle principal',
          suite: '',
          city: 'Madurai',
          country: 'India',
          zipCode: '08001',
        },
      },
      {
        customerName: 'Sakura Tanaka',
        status: 'priority',
        shippingService: 'express',
        address: {
          street: 'kyoto st',
          suite: 'Apt 201',
          city: 'Madurai',
          country: 'India',
          zipCode: '600-8017',
        },
      },
      {
        customerName: 'Hans Müller',
        status: 'express',
        shippingService: 'priority',
        address: {
          street: 'hamburg st',
          suite: '',
          city: 'Madurai',
          country: 'India',
          zipCode: '20095',
        },
      },
      
  ];